import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero } from "@/components/sections";
import { Reveal } from "@/components/reveal";
import { galleryImages, images, makeHead } from "@/lib/site-data";
export const Route = createFileRoute("/gallery")({ head: () => makeHead("Gallery | Aashiyana Guest House Sangla", "Explore real photographs of Aashiyana Guest House rooms, common spaces and mountain views in Sangla.", "/gallery"), component: GalleryPage });
function GalleryPage() { const [active,setActive]=useState<number|null>(null); useEffect(()=>{ const onKey=(event:KeyboardEvent)=>{ if(active===null)return; if(event.key==="Escape")setActive(null); if(event.key==="ArrowRight")setActive((active+1)%galleryImages.length); if(event.key==="ArrowLeft")setActive((active-1+galleryImages.length)%galleryImages.length); }; window.addEventListener("keydown",onKey); return()=>window.removeEventListener("keydown",onKey); },[active]); return <><PageHero eyebrow="Gallery" title="Inside Aashiyana. Outside, the Himalayas." copy="Real moments and spaces from the guest house and its remarkable Sangla setting." image={images.windowView} imageAlt="Himalayan view through a guest room window" /><section className="py-8 lg:py-14"><div className="mx-auto columns-1 gap-4 px-4 sm:columns-2 lg:columns-3">{galleryImages.map((image,index)=><Reveal key={image.src} delay={(index % 3) * 100}><button type="button" onClick={()=>setActive(index)} className="group mb-4 block w-full cursor-zoom-in overflow-hidden rounded-md bg-muted text-left" aria-label={`Open image: ${image.alt}`}><img src={image.src} alt={image.alt} className="w-full transition duration-700 group-hover:scale-[1.03] group-hover:brightness-90" /></button></Reveal>)}</div></section>{active!==null ? <div className="fixed inset-0 z-[60] grid place-items-center bg-gallery-overlay p-4 animate-fade-in" role="dialog" aria-modal="true" aria-label="Image viewer"><img src={galleryImages[active]?.src} alt={galleryImages[active]?.alt ?? "Aashiyana Guest House"} className="max-h-[88vh] max-w-[92vw] rounded-sm object-contain"/><Button size="icon" variant="secondary" className="absolute right-5 top-5 rounded-full" onClick={()=>setActive(null)} aria-label="Close image"><X/></Button><Button size="icon" variant="secondary" className="absolute left-4 top-1/2 rounded-full" onClick={()=>setActive((active-1+galleryImages.length)%galleryImages.length)} aria-label="Previous image"><ChevronLeft/></Button><Button size="icon" variant="secondary" className="absolute right-4 top-1/2 rounded-full" onClick={()=>setActive((active+1)%galleryImages.length)} aria-label="Next image"><ChevronRight/></Button><p className="absolute bottom-5 text-xs font-medium text-hero-foreground">{active+1} / {galleryImages.length}</p></div>:null}</>; }
